### ISSUE TITLE
Source and cygwin check can be made by bash

### ISSUE THREAD

**Issue by GustavHenning** [hoaphumanoid/scripts#2]
Hi! Nice script. I added [some code](https://github.com/GustavHenning/usefulBash/blob/master/setup_bashrc.sh) if you feel like automating the instructions.

Have a nice day!

**Comment by miguelgfierro** [comment]
Oh Thanks Gustav, would you like to do a PR? I would like to add your changes to the code

**Comment by GustavHenning** [comment]
Sure Miguel,  let me just make sure it works as intended!

**Comment by miguelgfierro** [comment]
BTW, very nice the `up` function. I think I might try to do `cs N` based on that!!!

**Comment by GustavHenning** [comment]
Thanks, there are many like it when one Googles for smart bash macros!

**Comment by miguelgfierro** [comment]
Updated in https://github.com/miguelgfierro/scripts/commit/5b9257f2544df2f4958607e6a6ec66841e74b6b3
